=== malejaj/cloud-and-edge-bundle-service/bundle/ordl_schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "ODRL Policy Schema",
  "description": "Schema to validate single or multiple ODRL policies.",
  "type": ["object", "array"],
  "items": {
    "type": "object",
    "properties": {
      "@context": {
        "type": ["string", "array"],
        "description": "ODRL context URI"
      },
      "uid": { "type": "string", "format": "uri" },
      "type": {
        "type": "string",
        "enum": ["Set", "Offer", "Agreement"]
      },
      "permission": {
        "type": "array",
        "items": {
          "type": "object",
          "properties": {
            "assignee": { "type": "string", "format": "uri" },
            "target": { "type": "string", "format": "uri" },
            "action": {
              "oneOf": [
                { "type": "string" },
                { "type": "object" },
                { "type": "array" }
              ]
            },
            "duty": {
              "type": "array",
              "items": {
                "type": "object",
                "properties": {
                  "assignee": { "type": "string", "format": "uri" },
                  "target": { "type": "string", "format": "uri" },
                  "action": {
                    "oneOf": [
                      { "type": "string" },
                      { "type": "object" }
                    ]
                  },
                  "constraint": { "type": "array" },
                  "informingParty": { "type": "string", "format": "uri" },
                  "informedParty": { "type": "string", "format": "uri" }
                },
                "required": ["action"]
              }
            },
            "constraint": { "type": "array" },
            "informingParty": { "type": "string", "format": "uri" },
            "informedParty": { "type": "string", "format": "uri" }
          },
          "required": ["target", "action"]
        }
      }
    },
    "required": ["@context", "uid", "type", "permission"]
  }
}

=== malejaj/cloud-and-edge-bundle-service/bundle/Policy2.json
[{
  "@context": "http://www.w3.org/ns/odrl.jsonld",
  "uid": "http://example.com/policy/enable-cap2-cap4-1",
  "type": "Set",
  "permission": [{
    "assignee": "http://example.com/edge/cap2",
    "target": "http://example.com/cap2/data",
    "action": "inform",
    "duty": [{
      "assignee": "http://example.com/cloud/cap4",
      "action": "NextPolicy",
      "uid": "http://example.com/policy/enable-cap2-cap4-2",
      "constraint": [{
        "leftOperand": "event",
        "operator": "eq",
        "rightOperand": "https://www.wikidata.org/wiki/Q131437603",
        "comment": "Object detected by cap2"
      }]
    }],
    "informingParty": "http://example.com/edge/cap2",
    "informedParty": "http://example.com/cloud/cap4"
  }]
},

{
  "@context": "http://www.w3.org/ns/odrl.jsonld",
  "uid": "http://example.com/policy/enable-cap2-cap4-2",
  "type": "Set",
  "permission": [{
      "assignee": "http://example.com/cloud/cap4",
      "target": "http://example.com/data/cap4-output",
      "action": "capture" ,
      "constraint": [{
          "leftOperand": "purpose",
          "operator": "eq",
          "rightOperand": "identification"
        }]
    }]
}]

=== malejaj/cloud-and-edge-bundle-service/bundle/Policy1.json
[{
  "@context": "http://www.w3.org/ns/odrl.jsonld",
  "uid": "http://example.com/policy/cause-cap2-cap1",
  "type": "Set",
  "permission": [{
      "assignee": "http://example.com/edge/cap1",
      "target": "http://example.com/change-direction",
      "action": "execute",
      "duty": [{
          "action": {
            "id": "inform",
            "refinement": [{
                "leftOperand": "event",
                "operator": "eq",
                "rightOperand": "https://www.wikidata.org/wiki/Q131437603"
              }]
          },
          "target": "http://example.com/cap2/data-ObjectDetected",
          "informedParty": "http://example.com/edge/cap1",
          "informingParty": "http://example.com/edge/cap2"
        }],
      "constraint": [{
       "leftOperand": "event",
              "operator": "lt",
              "rightOperand": { "@id": "odrl:policyUsage" }
        }]
    }]
}
]
